name: Deploy do Vite para o GitHub Pages

on:
  push:
    branches: ["main"] # Altere para "master" se a sua branch principal tiver esse nome

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Buildar o projeto
        run: npm run build

      - name: Fazer o upload do build (pasta dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
